<?php
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");

$APPLICATION->SetTitle("Мои заказы");
$APPLICATION->AddHeadString('<link rel="canonical" href="' . ((!empty($_SERVER['HTTPS'])) ? 'https' : 'http') . '://' . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'] . '"/>');

?>
<?php
$GLOBALS['arrFilter'] = array('PROPERTY_CUSTOMER' => $USER->GetID());
$APPLICATION->IncludeComponent(
	"bitrix:news", 
	"my_orders", 
	array(
		"ADD_ELEMENT_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"AJAX_OPTION_HISTORY" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"BROWSER_TITLE" => "-",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "Y",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"CHECK_DATES" => "Y",
		"DETAIL_ACTIVE_DATE_FORMAT" => "M j, Y",
		"DETAIL_DISPLAY_BOTTOM_PAGER" => "Y",
		"DETAIL_DISPLAY_TOP_PAGER" => "N",
		"DETAIL_FIELD_CODE" => array(
			0 => "ID",
			1 => "NAME",
			2 => "PREVIEW_TEXT",
			3 => "PREVIEW_PICTURE",
			4 => "DETAIL_TEXT",
			5 => "DETAIL_PICTURE",
			6 => "DATE_CREATE",
			7 => "",
		),
		"DETAIL_PAGER_SHOW_ALL" => "Y",
		"DETAIL_PAGER_TEMPLATE" => "",
		"DETAIL_PAGER_TITLE" => "Страница",
		"DETAIL_PROPERTY_CODE" => array(
			0 => "CUSTOMER",
			1 => "PHONE",
			2 => "EMAIL",
			3 => "ADDRESS",
			4 => "DELIVERY_METHOD",
			5 => "IS_INSURED",
			6 => "WEIGHT",
			7 => "VOLUME",
			8 => "STATUS",
			9 => "ORDER_CONTENT",
			10 => "NOTES",
			11 => "COMISSION",
			12 => "TOTAL_SUM_YUAN",
			13 => "TOTAL_SUM_RUB",
			14 => "GOODS_AND_DELIVERY_THROUGH_CHINA_COST_YUAN",
			15 => "GOODS_AND_DELIVERY_THROUGH_CHINA_COST_RUB",
			16 => "DELIVERY_COST_YUAN",
			17 => "DELIVERY_COST_RUB",
			18 => "",
		),
		"DETAIL_SET_CANONICAL_URL" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"DISPLAY_DATE" => "Y",
		"DISPLAY_NAME" => "Y",
		"DISPLAY_PICTURE" => "Y",
		"DISPLAY_PREVIEW_TEXT" => "Y",
		"DISPLAY_TOP_PAGER" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"IBLOCK_ID" => "8",
		"IBLOCK_TYPE" => "products",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"LIST_ACTIVE_DATE_FORMAT" => "j F Y",
		"LIST_FIELD_CODE" => array(
			0 => "ID",
			1 => "NAME",
			2 => "PREVIEW_TEXT",
			3 => "PREVIEW_PICTURE",
			4 => "DETAIL_TEXT",
			5 => "DETAIL_PICTURE",
			6 => "DATE_CREATE",
			7 => "",
		),
		"LIST_PROPERTY_CODE" => array(
			0 => "CUSTOMER",
			1 => "PHONE",
			2 => "EMAIL",
			3 => "ADDRESS",
			4 => "DELIVERY_METHOD",
			5 => "IS_INSURED",
			6 => "WEIGHT",
			7 => "VOLUME",
			8 => "STATUS",
			9 => "ORDER_CONTENT",
			10 => "NOTES",
			11 => "COMISSION",
			12 => "TOTAL_SUM_YUAN",
			13 => "TOTAL_SUM_RUB",
			14 => "GOODS_AND_DELIVERY_THROUGH_CHINA_COST_YUAN",
			15 => "GOODS_AND_DELIVERY_THROUGH_CHINA_COST_RUB",
			16 => "DELIVERY_COST_YUAN",
			17 => "DELIVERY_COST_RUB",
			18 => "TOTAL_COST_YUAN",
			19 => "TOTAL_COST_RUB",
		),
		"MESSAGE_404" => "",
		"META_DESCRIPTION" => "-",
		"META_KEYWORDS" => "-",
		"NEWS_COUNT" => "",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
		"PAGER_SHOW_ALL" => "N",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"PAGER_TITLE" => "Заказы",
		"PREVIEW_TRUNCATE_LEN" => "",
		"SEF_MODE" => "Y",
		"SET_LAST_MODIFIED" => "Y",
		"SET_STATUS_404" => "Y",
		"SET_TITLE" => "N",
		"SHOW_404" => "N",
		"SORT_BY1" => "ID",
		"SORT_BY2" => "SORT",
		"SORT_ORDER1" => "DESC",
		"SORT_ORDER2" => "ASC",
		"STRICT_SECTION_CHECK" => "N",
		"USE_CATEGORIES" => "N",
		"USE_FILTER" => "N",
		"USE_PERMISSIONS" => "Y",
		"USE_RATING" => "N",
		"USE_REVIEW" => "N",
		"USE_RSS" => "N",
		"USE_SEARCH" => "N",
		"USE_SHARE" => "N",
		"COMPONENT_TEMPLATE" => "my_orders",
		"SEF_FOLDER" => "/order/",
		"FILTER_NAME" => "arrFilter",
		"FILTER_FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"FILTER_PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"GROUP_PERMISSIONS" => array(
			0 => "1",
		),
		"SEF_URL_TEMPLATES" => array(
			"news" => "my_orders.php",
			"section" => "",
			"detail" => "#ELEMENT_ID#/",
		)
	),
	false
);?>


<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>